version: '3.4'


services:

  mysql:
    image: mysql:5.7.28
    comand: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=1
    networks:
      - backend-network
      - frontend-network
    restart: always
    depends-on:
      - mysql

  wordpress:
    image: wordpress
    ports: 
      - 80:80
    environment: 
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend-network
      - frontend-network
    restart: always
    depends-on:
      - mysql
volumes:

  mysql_data:
  wordpress_data:
networks:
  backend-network:
  frontend-network:
